sylius_twig_hooks:
    hooks:
        sylius_shop.base.header:
            latest_deals:
                component: 'NavigationMenu'
                priority: 150
        sylius_shop.homepage.index:
            latest_deals:
                component: 'Blank'
                priority: 0
            latest_products:
                component: 'Blank'
                priority: 0
            popular_products:
                component: 'PopularProducts'
                priority: 99 
